- name: install packages
  hosts: mongodb
  become: yes
  tasks:
  - name: install package
    ansible.builtin.yum:
      name: "{item.name}"
      state: "{item.state}"
    #This is list of map
    loop:
    - {name: 'nginx', state: 'absent'}
    - {name: 'postfix', state: 'installed'}