- name: loops example
  hosts: localhost  #you no need to give username and password bcz it is local host
  tasks:
  - name: print the names
    ansible.builtin.debug:
      msg: "Hello {{item}}"    # here item is special variable
    loop:
    - Pradeep
    - Raheem      #loops syntax is just loop: and under loop give list
    - John