- name: Install and run nginx
  hosts: mongodb
  be
  come: yes
  tasks:
  - name: Install nginx
    ansible.builtin.yum:
      name: nginx
      state: installed
  - name: Start nginx
    ansible.builtin.service:
      name: nginx
      state: started